#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorUpDown,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorGrab,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorNet,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	//Clear Debug stream (persists from last time
	//the program was run if you don't do this.)
	clearDebugStream();
	return;
}

void driveForward(int speed) {
	motor[motorLeft] = speed;
	motor[motorRight] = speed;
}

void stopDrive() {
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}

void driveUpDown(int power) {
	motor[motorUpDown] = power;
}

bool netClosed = true;
bool grabberClosed = true;

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		//Update joystick state variable
		getJoystickSettings(joystick);

		//store values for later use.
		int left  = joystick.joy1_y1;
		int right = joystick.joy1_y2;

		/*
		//Debug joystick positions.
		char buf[128];
		sprintf(buf,"Joystick Positions: %8d %8d",left,right);

		writeDebugStreamLine(buf);
		// */

		//If the left joystick is over a certain threshold,
		//set the left main propeller motor power to that
		//value. Otherwise, stop the motor.
		if (abs(left) > 25) {
			motor[motorLeft] = -(left-sgn(left)*25);
		} else {
			motor[motorLeft] = 0;
		}

		//If the right joystick is over a certain threshold,
		//set the right main propeller motor power to that
		//value. Otherwise, stop the motor.
		if (abs(right) > 25) {
			motor[motorRight] = (right-sgn(right)*25);
		} else {
			motor[motorRight] = 0;
		}

		//Open (btn 5) or Close (btn 7) the net grabber.
		//If neither button is pressed, stop the motor.
		if (joy1Btn(8)) {
			motor[motorUpDown] = 50;
		} else if (joy1Btn(6)) {
			motor[motorUpDown] = -50;
		} else {
			motor[motorUpDown] = 0;
		}

		//Open (btn 3) or Close (btn 1) the main grabber.
		//If neither button is pressed, stop the motor.
		if (joy1Btn(3)) {
			motor[motorGrab] = 50;
		} else if (joy1Btn(1)) {
			motor[motorGrab] = -50;
		} else {
			motor[motorGrab] = 0;
		}

		//Open (btn 5) or Close (btn 7) the net grabber.
		//If neither button is pressed, stop the motor.
		if (joy1Btn(5)) {
			writeDebugStreamLine("Open");
			motor[motorNet] = 50;
		} else if (joy1Btn(7)) {
			writeDebugStreamLine("Close");
			motor[motorNet] = -50;
		} else {
			motor[motorNet] = 0;
		}
	}
}
