#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorUpDown,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorGrab,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorNet,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	clearDebugStream();
  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void driveForward(int speed) {
	motor[motorLeft] = speed;
	motor[motorRight] = speed;
}

void stopDrive() {
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}

void driveUpDown(int power) {
	motor[motorUpDown] = power;
}

bool netClosed = true;
bool grabberClosed = true;

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
		getJoystickSettings(joystick);
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.



		int left  = joystick.joy1_y1;
		int right = joystick.joy1_y2;

		/*
		char buf[128];
		sprintf(buf,"Joystick Positions: %8d %8d",left,right);

		writeDebugStreamLine(buf);
		// */

  	if (abs(left) > 25) {
  		motor[motorLeft] = -(left-sgn(left)*25);
  	} else {
  		motor[motorLeft] = 0;
  	}

  	if (abs(right) > 25) {
  		motor[motorRight] = (right-sgn(right)*25);
  	} else {
  		motor[motorRight] = 0;
  	}

  	if (joy1Btn(8)) {
  		motor[motorUpDown] = 50;
  	} else if (joy1Btn(6)) {
  		motor[motorUpDown] = -50;
  	} else {
  		motor[motorUpDown] = 0;
  	}

  	if (joy1Btn(3)) {
  		motor[motorGrab] = 50;
  	} else if (joy1Btn(1)) {
  		motor[motorGrab] = -50;
  	} else {
  		motor[motorGrab] = 0;
  	}

  	if (joy1Btn(5)) {
  		writeDebugStreamLine("Open");
  		motor[motorNet] = 50;
  	} else if (joy1Btn(7)) {
  		writeDebugStreamLine("Close");
  		motor[motorNet] = -50;
  	} else {
  		motor[motorNet] = 0;
  	}
  }
}
